#!/bin/bash
#usage: ./report <username> <pwd>
#./save_page_as "https://keep.google.com/#home" --destination "./tro.html" > /dev/null
python webcrawl.py $1 $2
ruby convert.rb ../data/tolog.txt
mv temp.txt ../data/tolog.txt
runhaskell todo.hs
python plot.py
exit
